steps:
  # install dependencies
  - name: "gcr.io/cloud-builders/npm"
    args: ["install"]

  # build
  - name: "gcr.io/cloud-builders/npm"
    args: ["run", "build"]

  # deploy cloud function
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    args:
      - gcloud
      - functions
      - deploy
      - uspy-auth
      - --region=us-east1
      - --source=.
      - --memory=1024M
      - --entry-point=handle
      - --timeout=60s
      - --trigger-http
      - --runtime=nodejs18
      - --no-allow-unauthenticated
